# -*- coding: utf-8 -*-
"""AI4021 - HW1 - 2 - Python Tutorial 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WjQANHLE5nVMfAsX_IVkS_V5T-FvWLgF

**Problem 1:** Create a NumPy array of 20 random integers between 1 and 100. Calculate the mean, median, and standard deviation of the array.
"""



"""**Problem 2:** Create a Pandas DataFrame with three columns - 'Name', 'Age', and 'City' - and at least five rows of data. Perform a basic data exploration by displaying the first 3 rows, the last 2 rows, and a summary of statistics for the 'Age' column."""



"""**Problem 3:** Create a bar chart using Matplotlib to visualize the following data: Monthly sales for a store (January to May). Use appropriate labels and titles for the chart."""



"""**Problem 4:** Create two NumPy arrays, 'arr1' and 'arr2', both of size 5x5 with random integer values. Perform element-wise addition, subtraction, multiplication, and division between the two arrays."""



"""**Problem 5:** Given a Pandas DataFrame with information about employees, filter and display only the employees who are older than 30 years."""



"""**Problem 6:** Create a scatter plot using Matplotlib to visualize a dataset of 100 random (x, y) coordinates. Label the axes appropriately and give the plot a title."""



"""**Problem 7:** Create two NumPy matrices, 'matrix1' (2x3) and 'matrix2' (3x4), with random values. Perform matrix multiplication between the two matrices."""



"""**Problem 8:** Given a Pandas DataFrame containing sales data, calculate and display the total sales for each product category."""



"""**Problem 9:** Create a line chart using Matplotlib to visualize the population growth of a city over 10 years. Label the axes and provide a title."""



"""Problem: Given a Pandas DataFrame containing information about students, add a new column 'Grade' based on the following criteria:
* If 'Score' >= 90, Grade is 'A'
* If 'Score' >= 80, Grade is 'B'
* If 'Score' >= 70, Grade is 'C'
* If 'Score' < 70, Grade is 'D'
"""



"""**Problem 11:** You are given a dataset containing monthly sales data for three products (A, B, and C) over a two-year period. Your task is to perform various data analysis tasks using NumPy, Pandas, and Matplotlib.


*   Dataset:

```
import pandas as pd

data = {
    'Month': pd.date_range(start='2021-01-01', periods=24, freq='M'),
    'Product A Sales': [500, 480, 600, 750, 900, 850, 920, 1100, 1300, 1350, 1500, 1450, 1550, 1600, 1650, 1600, 1500, 1400, 1600, 1700, 1800, 1750, 1850, 1900],
    'Product B Sales': [300, 320, 400, 450, 500, 580, 700, 750, 820, 900, 950, 980, 1050, 1100, 1150, 1200, 1250, 1300, 1350, 1400, 1500, 1600, 1550, 1700],
    'Product C Sales': [200, 210, 250, 280, 320, 350, 380, 400, 420, 440, 460, 480, 500, 520, 540, 560, 580, 600, 620, 640, 660, 680, 700, 720]
}

sales_df = pd.DataFrame(data)
```
*  Tasks:
1. Calculate and display the total sales for each product over the two-year period.

2. Calculate and display the average monthly sales for each product.

3. Find the month with the highest sales for each product, and display the product and the sales value for that month.

4. Calculate and display the percentage change in sales for each product from January to December in the second year (2022).

5. Create a line chart using Matplotlib to visualize the monthly sales data for each product over the two-year period. Label the axes and provide a title for the chart.

6. Calculate the correlation between Product A and Product B sales. Is there a strong correlation between these two products? Display the correlation coefficient.

"""

