# -*- coding: utf-8 -*-
"""AI4021 - HW1 - 1 - Python Tutorial 1 - Sol.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YHJYNjrE2Klb32UEmitTB7jEG9HhP2HV

**Question 1:** Write a Python program that asks the user for their age. If the age is greater than or equal to 18, print "You are an adult." Otherwise, print "You are a minor."
"""

age = int(input("Enter your age: "))

if age >= 18:
    print("You are an adult.")
else:
    print("You are a minor.")

"""**Question 2:** Write a Python program to print the numbers from 1 to 10 using a for loop."""

for i in range(1, 11):
    print(i)

"""**Question 3:** Write a Python program to calculate the sum of all even numbers from 1 to 20 using a while loop."""

total = 0
i = 2

while i <= 20:
    total += i
    i += 2

print("Sum of even numbers from 1 to 20:", total)

"""**Question 4:** Define a function called multiply that takes two parameters and returns their product."""

def multiply(a, b):
    return a * b

"""**Question 5:** Create a class called Person with a constructor method that initializes the name and age attributes. Then, create an instance of the Person class and print the person's name and age."""

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

# Creating an instance of the Person class
person1 = Person("Alice", 25)
print("Name:", person1.name)
print("Age:", person1.age)

"""**Question 6:** Create a subclass called `Student` that inherits from the `Person` class. Add an additional attribute called `student_id` to the `Student` class. Create an instance of the `Student` class and print the student's name, age, and student ID."""

class Student(Person):
    def __init__(self, name, age, student_id):
        super().__init__(name, age)
        self.student_id = student_id

# Creating an instance of the Student class
student1 = Student("Bob", 20, "12345")
print("Name:", student1.name)
print("Age:", student1.age)
print("Student ID:", student1.student_id)

"""**Question 7:** Write a Python program that prompts the user to enter a number and then prints whether the number is prime or not. Create a function called `is_prime` that takes an integer as an argument and returns True if it's prime, and False otherwise."""

def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

number = int(input("Enter a number: "))
if is_prime(number):
    print(number, "is a prime number.")
else:
    print(number, "is not a prime number.")

"""**Question 8:** Write a Python program that calculates the factorial of a given number using a recursive function. Prompt the user for an integer input and print its factorial."""

def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

number = int(input("Enter an integer: "))
if number < 0:
    print("Factorial is not defined for negative numbers.")
else:
    result = factorial(number)
    print("Factorial of", number, "is", result)

"""**Question 9:** Create a class called `Rectangle` with attributes `width` and `height`. Add a method `calculate_area` that calculates and returns the area of the rectangle. Create an instance of the `Rectangle` class and print its area."""

class Rectangle:
    def __init__(self, width, height):
        self.width = width
        self.height = height

    def calculate_area(self):
        return self.width * self.height

# Creating an instance of the Rectangle class
rectangle1 = Rectangle(5, 8)
area = rectangle1.calculate_area()
print("Area of the rectangle:", area)

"""**Question 10:** Create a subclass called `Square` that inherits from the `Rectangle` class. Add a method `calculate_perimeter` to the `Square` class that calculates and returns the perimeter of the square. Create an instance of the `Square` class and print its perimeter."""

class Square(Rectangle):
    def __init__(self, side_length):
        # Call the constructor of the parent class (Rectangle)
        super().__init__(side_length, side_length)

    def calculate_perimeter(self):
        return 4 * self.width

# Creating an instance of the Square class
square1 = Square(4)
perimeter = square1.calculate_perimeter()
print("Perimeter of the square:", perimeter)

"""**Question 11:** Create a base class called `Animal` with attributes `name` and `species`. Provide a constructor to initialize these attributes and a method called `speak` that prints a generic message like "The animal makes a sound."
"""

class Animal:
    def __init__(self, name, species):
        self.name = name
        self.species = species

    def speak(self):
        print(f"{self.name} the {self.species} makes a sound.")

"""**Question 12:** Create a subclass called `Dog` that inherits from the `Animal` class. Add a constructor to initialize the `name`, `species`, and `breed` attributes specific to dogs. Override the `speak` method in the `Dog` class to print "Woof!"
"""

class Dog(Animal):
    def __init__(self, name, breed):
        super().__init__(name, "dog")
        self.breed = breed

    def speak(self):
        print(f"{self.name} the {self.breed} says Woof!")

"""**Question 13:** Create another subclass called `Cat` that inherits from the `Animal` class. Add a constructor to initialize the `name`, `species`, and `color` attributes specific to cats. Override the `speak` method in the `Cat` class to print "Meow!"
"""

class Cat(Animal):
    def __init__(self, name, color):
        super().__init__(name, "cat")
        self.color = color

    def speak(self):
        print(f"{self.name} the {self.color} cat says Meow!")

"""**Question 14:** Create instances of both the `Dog` and `Cat` classes and call their `speak` methods to demonstrate polymorphism."""

dog1 = Dog("Buddy", "Golden Retriever")
cat1 = Cat("Whiskers", "Calico")

dog1.speak()  # Output: "Buddy the Golden Retriever says Woof!"
cat1.speak()  # Output: "Whiskers the Calico cat says Meow!"